luau-lsp analyze out/Client/Analytics/Packages/Maid.lua \
--sourcemap=sourcemap.json \
--ignore="*.spec.luau" \
--ignore="*.spec.lua" \
--ignore="*.story.luau" \
--ignore="*.story.lua" \
--flag:LUAU_ENABLE_TIME_TRACE=true\
--flag:LuauTypeInferIterationLimit=0 \
--flag:LuauCheckRecursionLimit=0 \
--flag:LuauTypeInferRecursionLimit=0 \
--flag:LuauTarjanChildLimit=0 \
--flag:LuauTypeInferTypePackLoopLimit=0 \
--flag:LuauVisitRecursionLimit=0 \
--definitions=types/globalTypes.d.lua
